/*
@authoe ET
compare 2 numbers, one randomly generated


*/

public class GuessNumber {
	// declare instance variables 
	private int guess; // instance variable to store the number provided by the client/ user of this class
	private int secret; // instance variable to store the number generated by the computer
	private String message; // instance variable to show whether the two numbers are equal or one is higher than the other

	public GuessNumber() {
		secret = (int)(Math.random()*10) + 1; // generate the secret number between [1, 10]
		message = "you did not guess yet"; // initialize the message with a text to show that the 2 numbers have not been compared yet
	}

	//declare a setter method for each of the instance variables that can be set/ assigned a value provided by the user of this class
	// setter method for the guess instance variable
	public void setGuess(int guess){
		this.guess = guess;
	}


	// declare a getter method for each of the instance variables whose values should be made available to the other classes that use this class
	// for example, the class with the main() method which uses this instantiable class (i.e. Guess.java) would use the getters methods to retrieve the values to be printed
	//getter method to retrive the secret number generated by the computer
	public int getSecret(){
		return secret;
	}

	//getter method to retrive the message
	public String getMessage(){
		return message;
	}

	// the method which does the actual processing
	public void compute(){
		if (guess == secret) {
			message = "congratulations!";
		} else if (guess > secret){
			message = "guessed too high.";	
		} else{
			message = "guessed too low.";
		}
	}
}





public class GuessNumber{
	private double myGuess;
	private double sysGuess;
	private String message;

	if myGuess == sysGuess{
		public String Message("You're Right!"){
		return message;
		}

	}else if {myGuess > sysGuess
	 public String Message("Too big!"){
		return message;
		}
	}else if{myGuess < sysGuess
		public String Message("Too small!"){
			return message;
			}


	}else{
		public String Message("Fuck Off!"){
					return message;
			}
	}
}